---
name: ripple-starter
summary: Ripple starter
description: This workflow allow both incoming and outcoming transaction.
uri: https://github.com/esDataCo/tree/master/ripple-starter
action_bound: both
invokes:
  - ttPAYMENT
  - ttACCOUNT_SET
tags:
  - accept
publish: public

triggers:
  daily_run:
    scheduled: true
    trigger: system-cron
    parameters:
      schedule: '0 * * * *'
  accounts_feed_run:
    scheduled: false
    trigger: fb-watchman
    parameters:
      dir_interest: 'accounts_feed'
    map_content: exact

parameters:
  environment: hooks-testnet-v2.xrpl-labs.com
  account: rGjtrRRicdDhv8DGXNmr1TJhiDxSe6392K
  secret: ssBbXQNpTzQ7gPPAFAN4HE7Zn3vPz
  reason: "Starter: completed"

steps:
  trace_01:
    step: ripple-trace
    parameters:
      message: 'Starter: started'
  accept-01:
    step: ripple-accept
    dependsOn: trace_01
    parameters:
      reason: "$[parameters.reason]"
  account_info_01:
    step: ripple-account_info
    dependsOn: accept-01
    parameters:
      account: "$[parameters.account]"
  set_hook_test01:
    step: ripple-set_hooks
    dependsOn: account_info_01
    # status: disabled
    parameters:
      account_seq: $[steps.account_info_01.outputs.Sequence]
      hook_parameters:
        - HookParameter:
            HookParameterName: "key1"
            HookParameterValue: "1234523445"
