---
name: ripple-starter
summary: Ripple starter
description: This workflow allow both incoming and outcoming transaction.
uri: https://github.com/esDataCo/tree/master/ripple-starter
action_bound: both
invokes:
  - ttPAYMENT
  - ttACCOUNT_SET
tags:
  - accept
publish: public

triggers:
  daily_run:
    scheduled: false
    trigger: system-cron
    parameters:
      schedule: '0 * * * *'
  accounts_feed_run:
    scheduled: false
    trigger: fb-watchman
    parameters:
      dir_interest: 'accounts_feed'
    map_content: exact

parameters:
  environment: hooks-testnet-v2.xrpl-labs.com
  account: rGjtrRRicdDhv8DGXNmr1TJhiDxSe6392K
  reason: "Starter: completed"

steps:
  trace_01:
    step: ripple-trace
    parameters:
      message: 'Starter: started'
  accept-01:
    step: ripple-accept
    dependsOn: trace_01
    parameters:
      reason: "$[parameters.reason]"
  account_info_01:
    step: ripple-account_info
    dependsOn: accept-01
    parameters:
      account: "$[parameters.account]"
  vault_kv_get_01:
    step: hashicorp-vault_kv_get
    dependsOn: account_info_01
    parameters:
      token: 'hvs.5iq6HaGCHTPSpYqJz2HQFFbE'
      path: secret/data/users/cheehuan@esdata.co/accounts/$[parameters.account]
  set_hook_test01:
    step: ripple-set_hooks
    dependsOn: vault_kv_get_01
    # status: disabled
    parameters:
      account_sequence: $[steps.account_info_01.outputs.Sequence]
      secret: $[steps.vault_kv_get_01.outputs.secret]
      hook_namespace: "$[name]"
      hook_parameters:
        - HookParameter:
            HookParameterName: "key1"
            HookParameterValue: "1234523445"
  message_01:
    step: slack-message
    dependsOn: set_hook_test01
    skip: ?[$[steps.set_hook_test01.status] != completed]
    parameters:
      text: Account ($[parameters.account]) hook deployed successfully with namespace $[steps.set_hook_test01.parameters.hook_namespace].
  message_02:
    step: system-email
    dependsOn: message_01
    skip: ?[$[steps.set_hook_test01.status] != completed]
    parameters:
      recipient: cheehuan@esdata.co
      subject: XRPL Set Hook activitities
      text_body: $[parameters.account], hook deployed successfully with namespace $[steps.set_hook_test01.parameters.hook_namespace]
      html_body: <h1>$[parameters.account], hook deployed successfully with namespace $[steps.set_hook_test01.parameters.hook_namespace]</h1>
